version: "3"

services:

  virtuoso:
    container_name: virtuoso
    image: tenforce/virtuoso:latest
    environment:
      DBA_PASSWORD: dba
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: https://w3id.org/um/ids/graph
    volumes:
      - ./data/virtuoso:/data
    ports:
      - 8890:8890
      - 1111:1111

  jupyterlab:
    container_name: jupyterlab
    # image: ghcr.io/vemonet/jupyterlab
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./data/jupyterlab:/notebooks
    environment:
      - PASSWORD=password
      - GIT_URL=https://github.com/vemonet/translator-sparql-notebook
      # Bonus variables to deploy on IDS servers with HTTPS encryption (using https://github.com/nginx-proxy)
      - VIRTUAL_HOST=jupyterlab.137.120.31.102.nip.io
      - LETSENCRYPT_HOST=jupyterlab.137.120.31.102.nip.io
      - VIRTUAL_PORT=8888
